spring:
  mail:
    host: smtp.gmail.com
    username: codejava.net@gmail.com
    password: your_email_password
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
